# Generated by Django 4.1.7 on 2023-03-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_group_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
