# Generated by Django 4.1.7 on 2023-03-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_group_options_alter_group_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('can_notice', 'notice'),)},
        ),
    ]
